//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlamHaven.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hakkimizdas
    {
        public int ID { get; set; }
        public string Baslık { get; set; }
        public string Acıklama { get; set; }
    }
}
