//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlamHaven.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hizmetlers
    {
        public int ID { get; set; }
        public string Baslık1 { get; set; }
        public string Acıklama1 { get; set; }
        public string Baslık2 { get; set; }
        public string Acıklama2 { get; set; }
        public string Baslık3 { get; set; }
        public string Acıklama3 { get; set; }
    }
}
